### PR TITLE
Use normal build script

### LINKED ISSUE #1: Recipe not building
### Comment:

The recipe passed the checks on the PR (see https://github.com/conda-forge/staged-recipes/pull/18775), however it is not build in this repository (see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=505573&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=116 for the error).
@conda-forge/help-python do you have an idea on how to solve this? It seems that it is linked to the option `--use-deprecated=out-of-tree-build` for pip (see https://github.com/conda-forge/staged-recipes/pull/18775#issuecomment-1121134387)

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #1 

Pyproject can be quite temperamental so let's try this.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Review by rcaneill — APPROVED** [review]
Thanks a lot for your help Bastian!
This looks fine to me.
@DocOtak is not very available for the moment (field work), and I am leading this 1st try to make the receipe, so I think that we can merge before his review

**Comment by BastianZim** [comment]
Happy to help!

> so I think that we can merge before his review

Yes, in conda-forge it's not necessary to wait for the other maintainers, only if you have an internal agreement.

**Comment by BastianZim** [comment]
You'll need to merge the PR though as you're the maintainer here.

**Pull request merged**
